"use client";
import { useState } from "react";
import styles from "./securityops.module.css";
type ApiError={error?:string}; type Job={id:string;tool:string;target:string;status:string}; type Finding={id:string;title:string;severity:string;status:string;vulnerability_class:string}; type SearchResult={id:string;result_type:string;value:string};
const tools=["subfinder","httpx","naabu","katana","nuclei","dalfox","sqlmap"], validationTools=new Set(["nuclei","dalfox","sqlmap"]);
async function jsonRequest<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{"content-type":"application/json",...init?.headers}}),payload=await response.json() as T&ApiError;if(!response.ok)throw new Error(payload.error||`Request failed (${response.status}).`);return payload}
export default function ExecutionConsole(){
 const [programName,setProgramName]=useState("Authorized bug-bounty program"),[platform,setPlatform]=useState("hackerone"),[authorizationRef,setAuthorizationRef]=useState(""),[includeScope,setIncludeScope]=useState("example.com"),[excludeScope,setExcludeScope]=useState(""),[programId,setProgramId]=useState(""),[tool,setTool]=useState("subfinder"),[target,setTarget]=useState("example.com"),[approved,setApproved]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[query,setQuery]=useState(""),[results,setResults]=useState<SearchResult[]>([]),[findings,setFindings]=useState<Finding[]>([]),[rationale,setRationale]=useState(""),[evidence,setEvidence]=useState(""),[message,setMessage]=useState("Create a program to unlock controlled execution."),[busy,setBusy]=useState(false);
 async function createProgram(){setBusy(true);try{const payload=await jsonRequest<{program:{id:string}}>("/api/programs",{method:"POST",body:JSON.stringify({name:programName,platform,authorizationRef,rateLimit:5,concurrency:2})}),id=payload.program.id;await jsonRequest(`/api/programs/${id}/scopes`,{method:"POST",body:JSON.stringify({kind:includeScope.startsWith("*.")?"wildcard":"domain",value:includeScope,decision:"include"})});if(excludeScope.trim())await jsonRequest(`/api/programs/${id}/scopes`,{method:"POST",body:JSON.stringify({kind:excludeScope.startsWith("*.")?"wildcard":"domain",value:excludeScope,decision:"exclude"})});setProgramId(id);setMessage(`Program ready: ${id}`)}catch(error){setMessage(error instanceof Error?error.message:"Program setup failed.")}finally{setBusy(false)}}
 async function launchJob(){setBusy(true);try{const payload=await jsonRequest<{job:Job}>("/api/jobs",{method:"POST",body:JSON.stringify({programId,tool,target,validationApproved:validationTools.has(tool)?approved:false})});setJobs(current=>[payload.job,...current]);setMessage(`Job queued: ${payload.job.id}`)}catch(error){setMessage(error instanceof Error?error.message:"Job failed.")}finally{setBusy(false)}}
 async function loadFindings(){if(!programId)return;const payload=await jsonRequest<{findings:Finding[]}>(`/api/findings?programId=${encodeURIComponent(programId)}`);setFindings(payload.findings)}
 async function syncJob(job:Job){setBusy(true);try{const payload=await jsonRequest<{status:string;importedResults:number}>(`/api/jobs/${job.id}/sync`,{method:"POST",body:"{}"});setJobs(current=>current.map(item=>item.id===job.id?{...item,status:payload.status}:item));setMessage(`${payload.status}: imported ${payload.importedResults} normalized results.`);await loadFindings()}catch(error){setMessage(error instanceof Error?error.message:"Sync failed.")}finally{setBusy(false)}}
 async function cancelJob(job:Job){try{await jsonRequest(`/api/jobs/${job.id}/cancel`,{method:"POST",body:"{}"});setJobs(current=>current.map(item=>item.id===job.id?{...item,status:"cancelled"}:item))}catch(error){setMessage(error instanceof Error?error.message:"Cancellation failed.")}}
 async function search(){try{const payload=await jsonRequest<{results:SearchResult[]}>(`/api/results?programId=${encodeURIComponent(programId)}&q=${encodeURIComponent(query)}`);setResults(payload.results);setMessage(`${payload.results.length} matching results.`)}catch(error){setMessage(error instanceof Error?error.message:"Search failed.")}}
 async function validate(finding:Finding,decision:"approve"|"reject"|"needs_more_evidence"){try{if(evidence.trim())await jsonRequest(`/api/findings/${finding.id}/evidence`,{method:"POST",body:JSON.stringify({kind:"note",content:evidence})});const payload=await jsonRequest<{status:string}>(`/api/findings/${finding.id}/validate`,{method:"POST",body:JSON.stringify({decision,rationale})});setFindings(current=>current.map(item=>item.id===finding.id?{...item,status:payload.status}:item));setMessage(`Finding marked ${payload.status}.`)}catch(error){setMessage(error instanceof Error?error.message:"Validation failed.")}}
 async function downloadReport(finding:Finding,reportPlatform:"hackerone"|"bugcrowd"){const response=await fetch(`/api/findings/${finding.id}/report`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({platform:reportPlatform})});if(!response.ok){const payload=await response.json() as ApiError;setMessage(payload.error||"Report generation failed.");return}const blob=await response.blob(),href=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=href;anchor.download=`aifix3r-${finding.id}-${reportPlatform}.md`;anchor.click();URL.revokeObjectURL(href)}
 return <section className={styles.console}><div className={styles.consoleHead}><div><span className="eyebrow">CONTROLLED EXECUTION</span><h2>Authorized worker console</h2></div><p>{message}</p></div><div className={styles.consoleGrid}>
 <article><h3>1. Program and scope</h3><label>Program name<input value={programName} onChange={event=>setProgramName(event.target.value)}/></label><div className={styles.fields}><label>Platform<select value={platform} onChange={event=>setPlatform(event.target.value)}><option value="hackerone">HackerOne</option><option value="bugcrowd">Bugcrowd</option><option value="private">Private</option><option value="lab">Owned lab</option></select></label><label>Authorization reference<input value={authorizationRef} onChange={event=>setAuthorizationRef(event.target.value)} placeholder="Program URL or approval ID"/></label></div><div className={styles.fields}><label>Include scope<input value={includeScope} onChange={event=>setIncludeScope(event.target.value)}/></label><label>Exclude scope<input value={excludeScope} onChange={event=>setExcludeScope(event.target.value)} placeholder="staging.example.com"/></label></div><button onClick={()=>void createProgram()} disabled={busy||authorizationRef.trim().length<3}>Create guarded program</button></article>
 <article><h3>2. Run allowlisted tool</h3><div className={styles.fields}><label>Tool<select value={tool} onChange={event=>{setTool(event.target.value);setApproved(false)}}>{tools.map(name=><option key={name}>{name}</option>)}</select></label><label>Target<input value={target} onChange={event=>setTarget(event.target.value)}/></label></div>{validationTools.has(tool)&&<label className={styles.auth}><input type="checkbox" checked={approved} onChange={event=>setApproved(event.target.checked)}/><span><strong>Approve validation</strong>I reviewed the rules and approve this bounded validation job.</span></label>}<button onClick={()=>void launchJob()} disabled={busy||!programId||(validationTools.has(tool)&&!approved)}>Queue controlled job</button><div className={styles.jobs}>{jobs.map(job=><div key={job.id}><span><strong>{job.tool}</strong> {job.target}<small>{job.status} · {job.id.slice(0,8)}</small></span><button onClick={()=>void syncJob(job)}>Sync</button>{["queued","running"].includes(job.status)&&<button onClick={()=>void cancelJob(job)}>Cancel</button>}</div>)}</div></article></div>
 <div className={styles.consoleGrid}><article><h3>3. Search normalized results</h3><div className={styles.search}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="host, URL, severity, template…"/><button onClick={()=>void search()} disabled={!programId}>Search</button></div><div className={styles.resultList}>{results.map(result=><div key={result.id}><span>{result.result_type}</span><code>{result.value}</code></div>)}</div></article>
 <article><h3>4. Human validation and report</h3><label>Sanitized evidence note<textarea value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><label>Validation rationale<textarea value={rationale} onChange={event=>setRationale(event.target.value)}/></label><button onClick={()=>void loadFindings()} disabled={!programId}>Load candidates</button><div className={styles.findings}>{findings.map(finding=><div key={finding.id}><strong>{finding.title}</strong><small>{finding.severity} · {finding.status} · {finding.vulnerability_class}</small><div><button onClick={()=>void validate(finding,"approve")}>Approve</button><button onClick={()=>void validate(finding,"reject")}>Reject</button>{finding.status==="validated"&&<><button onClick={()=>void downloadReport(finding,"hackerone")}>H1 report</button><button onClick={()=>void downloadReport(finding,"bugcrowd")}>Bugcrowd</button></>}</div></div>)}</div></article></div></section>
}
